In [78]:
import numpy as np

array = np.random.randint(1, 21, size=(3, 3))
print("2D Array:")
print(array)

2D Array:
[[ 5 11  4]
 [ 6 17 19]
 [14  7  9]]


In [79]:
print("Shape of array:", array.shape)
print("Size of array:", array.size)
print("Data type of array:", array.dtype)

Shape of array: (3, 3)
Size of array: 9
Data type of array: int32


In [80]:
print("First row of the array:", array[0])
print("Last column of the array:", array[:, -1])

First row of the array: [ 5 11  4]
Last column of the array: [ 4 19  9]


In [81]:
print("Sum of all elements:", array.sum())
print("Sum of elements in row:", array.sum(axis=1))
print("Sum of elements in column:", array.sum(axis=0))

Sum of all elements: 92
Sum of elements in row: [20 42 30]
Sum of elements in column: [25 35 32]


In [82]:
oneDarra = np.arange(10, 31, 4)
print("1D Array:", oneDarra)

1D Array: [10 14 18 22 26 30]


In [83]:
twoDarr = one_d_array.reshape(2, 3)
print("2D Array (reshaped):")
print(twoDarr)

2D Array (reshaped):
[[10 14 18]
 [22 26 30]]


In [84]:
divby5 = two_d_array[two_d_array % 5 == 0]
print("Divisible by 5:", divby5)

Divisible by 5: [10 30]
